#!/bin/bash

opak=""
soubor=""
if [ "$1"="-r" ] ; then opak="-r"
        else if [ "$1"="" ] ; then soubor="."
             else soubor="$1";
	     fi
fi
if [ $2 = "-r" ]; then opak="-r"; fi

cd $soubor

if [ $opak="" ]; then 
find -type f | grep [^a-z] | while read line; do 
				dir=$line
				newdir=`echo $line | tr A-Z a-z`
				if [ -e "$newdir" ]; then
						echo "Soubor $line nelzeprejmenovat"
						     else
						mv -f "dir" "newdir"
				fi
				done   
else
find -type f | grep [^A-Z] | while read line; do
                                dir=$line
                                newdir=`echo $line | tr a-z A-Z`
                                if [ -e "$newdir" ]; then
                                                echo "Soubor $line nelze prejmenovat"
                                                     else
                                                mv -f "dir" "newdir"
				fi
				done
fi
